sudo: required
services:
  - docker

before_intstall:
  - docker build -t mohmousad/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true mohmousad/docker-react npm run test

language: generic
